project_id = "zrnaebbyatqlhfqmibdj"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-subscription-status]
verify_jwt = false

[functions.import-letterboxd-list]
verify_jwt = true